// Generated by dedot cli
import type {
  GenericContractTx,
  GenericContractTxCall,
  ContractTxOptions,
  ContractSubmittableExtrinsic,
} from 'dedot/contracts';
import type { GenericSubstrateApi } from 'dedot/types';

export interface ContractTx<ChainApi extends GenericSubstrateApi> extends GenericContractTx<ChainApi> {
  /**
   * Sets `message` to the given value.
   *
   * @param {string} newValue
   * @param {ContractTxOptions} options
   *
   * @selector 0x1fe7426f
   **/
  setMessage: GenericContractTxCall<
    ChainApi,
    (newValue: string, options: ContractTxOptions) => ContractSubmittableExtrinsic<ChainApi>
  >;
}
